name: coap
channels:
  - conda-forge
  - iopath
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - aom=3.9.1=hac33072_0
  - blosc=1.21.6=he440d0b_1
  - brunsli=0.1=he3183e4_1
  - bzip2=1.0.8=hda65f42_8
  - c-blosc2=2.17.1=h3122c55_0
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - charls=2.4.2=h59595ed_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - dav1d=1.2.1=hd590300_0
  - giflib=5.2.2=hd590300_0
  - icu=75.1=he02047a_0
  - imagecodecs=2024.12.30=py39h490a228_1
  - imageio=2.37.0=pyhfb79c49_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - iopath=0.1.9=py39
  - jxrlib=1.1=hd590300_3
  - lazy-loader=0.4=pyhd8ed1ab_2
  - lazy_loader=0.4=pyhd8ed1ab_2
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.45=default_hbd61a6d_104
  - lerc=4.0.0=h0aef613_1
  - libaec=1.1.4=h3f801dc_0
  - libavif16=1.3.0=h6395336_2
  - libblas=3.11.0=2_h4a7cf45_openblas
  - libbrotlicommon=1.1.0=hb03c661_4
  - libbrotlidec=1.1.0=hb03c661_4
  - libbrotlienc=1.1.0=hb03c661_4
  - libcblas=3.11.0=2_h0358290_openblas
  - libdeflate=1.24=h86f0d12_0
  - libexpat=2.7.3=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=he0feb66_13
  - libgcc-ng=15.2.0=h69a702a_13
  - libgfortran=15.2.0=h69a702a_14
  - libgfortran-ng=15.2.0=h69a702a_14
  - libgfortran5=15.2.0=h68bc16d_14
  - libgomp=15.2.0=he0feb66_13
  - libhwy=1.3.0=h4c17acf_1
  - libjpeg-turbo=3.1.2=hb03c661_0
  - libjxl=0.11.1=h6cb5226_4
  - liblapack=3.11.0=2_h47877c9_openblas
  - liblzma=5.8.1=hb9d3cd8_2
  - libnsl=2.0.1=hb9d3cd8_1
  - libopenblas=0.3.30=pthreads_h94d23a6_4
  - libpng=1.6.51=h421ea60_0
  - libsqlite=3.51.0=hee844dc_0
  - libstdcxx=15.2.0=h934c35e_13
  - libstdcxx-ng=15.2.0=hdf11a46_13
  - libtiff=4.7.1=h8261f1e_0
  - libuuid=2.41.2=he9a06e4_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - libzopfli=1.0.3=h9c3ff4c_0
  - lz4-c=1.10.0=h5888daf_1
  - ncurses=6.5=h2d0b736_3
  - networkx=3.2.1=pyhd8ed1ab_0
  - numpy=2.0.2=py39h9cb892a_1
  - openjpeg=2.5.4=h55fea9a_0
  - openssl=3.6.0=h26f9b46_0
  - packaging=25.0=pyh29332c3_1
  - pillow=11.3.0=py39h15c0740_0
  - pip=25.2=pyh8b19718_0
  - portalocker=3.2.0=py39hf3d152e_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - python=3.9.23=hc30ae73_0_cpython
  - python_abi=3.9=8_cp39
  - pywavelets=1.6.0=py39hd92a3bb_0
  - rav1e=0.7.1=h8fae777_3
  - readline=8.2=h8c095d6_2
  - scikit-image=0.24.0=py39h3b40f6f_3
  - scipy=1.13.1=py39haf93ffa_0
  - setuptools=80.9.0=pyhff2d567_0
  - snappy=1.2.2=h03e3b7b_1
  - svt-av1=3.1.2=hecca717_0
  - tifffile=2024.6.18=pyhd8ed1ab_0
  - tk=8.6.13=noxft_ha0e22de_103
  - tqdm=4.67.1=pyhd8ed1ab_1
  - trimesh=4.7.4=pyh7b2049a_0
  - tzdata=2025b=h78e105d_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - xorg-libxau=1.0.12=hb03c661_1
  - xorg-libxdmcp=1.1.5=hb03c661_1
  - zfp=1.0.1=h909a3a2_3
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib-ng=2.2.5=hde8ca8f_1
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
    - coap==1.0.0
    - smplx==0.1.28
    - torch==2.7.1+cu128
    - torchaudio==2.7.1+cu128
    - torchvision==0.22.1+cu128

prefix: "/home/joeychen/miniforge3/envs/coap"
